server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ecommerce}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
spring.jpa.open-in-view=false

twilio.account.sid=ACc7a57ba9e25881852256964da9068758
twilio.auth.token=4ec029d8d28a7e0b6d9157c28f531dff
twilio.verify.service.sid=VA61d29a34295ccd2d8b67476e830af235
